version = 1

[[annotations]]
path = ["code_octarine.ogg"]
SPDX-FileCopyrightText = "By AftrLite(GitHub) for Cosmic Cult. Made using a combination of (Creative Commons 0) samples from freesound.org and personally-recorded foley."
SPDX-License-Identifier = "CC-BY-SA-3.0"
SPDX-FileAttributionText = "https://freesound.org/"
