version = 1

[[annotations]]
path = ["BuildChecker/**", "BuildFiles/**", "Content.Benchmarks/**", "Content.Docfx/**", "Content.IntegrationTests/**", "Content.MapRenderer/**", "Content.Packaging/**", "Content.PatreonParser/**", "Content.Replay/**", "Content.Server.Database/**", "Content.Shared.Database/**", "Content.Tests/**", "Content.Tools/**", "Content.YAMLLinter/**", "Pow3r/**", "Tools/**", "bors.toml", "CODE_OF_CONDUCT.md", "Directory.Packages.props", "flake.lock", "flake.nix", "global.json", "nuget.config", "omnisharp.json", "README.md", "runclient.bat", "runclient.sh", "runclient-Tools.bat", "runclient-Tools.sh", "runserver.bat", "runserver.sh", "runserver-Tools.bat", "runserver-Tools.sh", "RUN_THIS.py", "SECURITY.md", "shell.nix", "SpaceStation14.sln", "SpaceStation14.sln.DotSettings", ".editorconfig", ".envrc", ".gitattributes", ".github/**", ".gitignore", ".gitmodules", ".run/**", ".vscode/**.json", ".github/rsi-schema.json"]
SPDX-FileCopyrightText = "Wizard's Den Contributors"
SPDX-License-Identifier = "LicenseRef-WizardsDen"

[[annotations]]
path = [".github/workflows/reuse.yml"]
SPDX-FileCopyrightText = "2025 Janet Blackquill <uhhadd@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"
