version = 1

[[annotations]]
path = ["A**", "B**", "C**", "D**", "E**", "F**", "G**", "H**", "I**", "J**", "K**", "L**", "M**", "N**", "O**", "P**", "Q**", "R**", "S**", "T**", "U**", "V**", "W**", "X**", "Y**", "Z**", "*"]
SPDX-FileCopyrightText = "Wizard's Den Contributors"
SPDX-License-Identifier = "LicenseRef-WizardsDen"
