version = 1

[[annotations]]
path = ["*", "ConfigPresets/Build/*", "ConfigPresets/WizardsDen/*"]
SPDX-FileCopyrightText = "Wizard's Den Contributors"
SPDX-License-Identifier = "LicenseRef-WizardsDen"
