version = 1

[[annotations]]
path = ["*.png"]
SPDX-FileCopyrightText = "Unknown from CEV-Eris"
SPDX-License-Identifier = "CC-BY-SA-3.0"
SPDX-FileAttributionText = "https://github.com/discordia-space/CEV-Eris/blob/0b3ab17dbad632ddf738b63900ef8df1926bba47/icons/obj/tables.dmi"
