version = 1

[[annotations]]
path = ["*.png"]
SPDX-FileCopyrightText = "AftrLite"
SPDX-License-Identifier = "LicenseRef-CosmicCult"

[[annotations]]
path = ["tenebraeconspiracybook.png"]
SPDX-FileCopyrightText = "Sha-Seng"
SPDX-License-Identifier = "LicenseRef-CosmicCult"
